[build]
# https://github.com/rust-lang/rust/pull/124129
# https://github.com/dtolnay/linkme/pull/88
rustflags = ["-Zlinker-features=-lld"]

[env]
# If we're running in the project workspace, then we should set the workspace env var so we read/write to/from files relative to the workspace.
CARGO_WORKSPACE_DIR = { value = "", relative = true }

[target.x86_64-unknown-linux-gnu]
linker = "clang"