[env]
# read/write to/from files relative to the workspace even when running in this
# directory
CARGO_WORKSPACE_DIR = { value = "", relative = true }

[target.x86_64-unknown-linux-gnu]
linker = "clang"