[build]
rustflags = ["-C", "target-cpu=native"]

[env]
RUST_BACKTRACE = "1"
RUST_TEST_NOCAPTURE = "1"

[term]
verbose = true
color = 'auto'

[target.x86_64-unknown-linux-gnu]
linker = "clang"
#rustflags = ["-C", "target-cpu=native", "-C", "link-arg=-fuse-ld=/usr/bin/mold", "-Z", "threads=2", "-C", "debuginfo=2"]
rustflags = ["-C", "target-cpu=native", "-C", "link-arg=-fuse-ld=/usr/bin/mold", "-C", "debuginfo=2"]
