[package]
name = "hacking"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
line-index = "0.1.1"
pest = "2.7.13"
pest_derive = "2.7.13"
serde_json = "1.0.128"
tokio = { version = "1.40.0", features = ["full"] }
tower-lsp = "0.20.0"
tracing = "0.1.40"
url = "2.5.2"
