name: Docker Build & Push

on:
  push:
    branches: [develop, main]
  release:
    types: [created]

env:
  REGISTRY: ghcr.io

jobs:
  docker:
    name: Build and push leader and worker docker images to GitHub Container Registry
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels)
        id: meta_leader
        uses: docker/metadata-action@v5
        with:
          images: |
            name=${{ env.REGISTRY }}/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Push to GitHub Container Registry
        uses: docker/build-push-action@v3
        with:
          push: true
          # platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta_leader.outputs.tags }}
          labels: ${{ steps.meta_leader.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
