name: Docker Build & Run

on:
  push:
    branches: [develop, main]
  pull_request:
    branches:
      - "**"
  workflow_dispatch:
    branches:
      - "**"

jobs:
  docker:
    name: Build and run for sanity check leader and worker docker images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build leader docker container
        run: |
          docker build --progress plain -t leader:${{ github.ref_name }} -f leader.Dockerfile .

      - name: Run leader docker container
        run: |
          docker run -it leader:${{ github.ref_name }} --help