name: Shellcheck
on:
  push:
    paths: 
      - 'scripts/**'
  pull_request:
    branches:
      - "**"

jobs:
  shellcheck_scripts:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - name: Install shellcheck
        run: sudo apt-get install shellcheck

      - name: Run shellcheck
        run: |
          cd scripts
          shellcheck ./*.sh
